# Generated by Django 4.1.3 on 2022-12-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Person',
        ),
    ]
